---
# Basic SSH configuration
sshd_permit_root_login: prohibit-password
sshd_log_level: VERBOSE
sshd_x11_forwarding: "yes"
sshd_print_motd: "no"

# Security settings
sshd_allowed_groups:
  - root

# IP Ranges for security matches
sshd_admin_networks:
  - 192.168.0.0/16

