---
- name: Install necessary packages
  package:
    name: 
      - openssh
      - openssh-server
    state: present

- name: Deploy sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart sshd

- name: Ensure sshd service is enabled and running
  service:
    name: sshd
    state: started
    enabled: yes 